web/fairdy/urls.py
from django.urls import path

from .views import *

app_name = 'fairdy'

urlpatterns = [
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('visualize/', visualize, name='visualize'),
    path('run/', run_simulation, name='run_simulation'),
    path('csv/', get_csv, name='get_csv'),
    path('about_simulation/', about_simulation, name='about_simulation'),
    path('help/getting_started/', help_getting_started, name='help_getting_started'),
    path('help/run_simulation/', help_run_simulation, name='help_run_simulation'),
    path('help/compare_download/', help_compare_download, name='help_compare_download'),
    # should be last since it will check any string (after /fairdy/) to see if it is an installed code
    path('<str:code_type>/', index, name='codes'),
]

web/web/urls.py
from django.urls import path, include

from fairdy.views import *

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('accounts/', include('accounts.urls')),
    path('fairdy/', include('fairdy.urls')),
]

web/fairdy/models.py
import base64
from io import BytesIO

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from matplotlib import pyplot

from accounts.models import FairdyUser


class Simulation(models.Model):
    # Erasure Codes which are currently installed on FaiRDy web framework
    class Codes(models.TextChoices):
        REPLICATION = 'REP'
        REED_SOLOMON = 'RS'
        GENERALIZED_PYRAMID = 'GP'

    # Storage fault modes available from fairdypy module
    class StorageLocationModes(models.TextChoices):
        RANDOM = 'random'
        EQUAL_SHUFFLE = 'equal_shuffle'
        HASH_BLOCK_INDEX = 'hash_block_index'

    # FIELDS FOR SIMULATION MODEL
    code_type = models.CharField(
        'Erasure Code',
        max_length=10,
        choices=Codes.choices
    )
    k_value = models.PositiveIntegerField(
        '(k) data',
        validators=[MinValueValidator(1)]
    )
    m_value = models.PositiveIntegerField(
        '(m) redundancy',
        validators=[MinValueValidator(1)]
    )
    n_value = models.PositiveIntegerField(
        '(n) total',
        validators=[MinValueValidator(1)]
    )
    num_stripes = models.PositiveIntegerField(
        'Stripes per Storage System',
        validators=[MinValueValidator(1)]
    )
    num_cycles = models.PositiveIntegerField(
        'Number of Cycles',
        validators=[MinValueValidator(1)]
    )
    p_error = models.FloatField(
        '(p_error) Probability of Block Failure',
        validators=[MinValueValidator(0), MaxValueValidator(1)]
    )
    storage_location_mode = models.CharField(
        'Storage Location Mode',
        max_length=50,
        choices=StorageLocationModes.choices,
        blank=True,
        null=True
    )
    num_storage_locations = models.PositiveIntegerField(
        'Number of Storage Locations',
        validators=[MinValueValidator(1)]
    )
    lazy_heal_threshold = models.PositiveIntegerField(
        'Lazy Heal Threshold',
        default=1,  # '1' for for eager heal, for GPC sims this field holds the horiz. threshold, vert. is on GPC model
        validators=[MinValueValidator(1)]
    )
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True)
    fairdy_user = models.ForeignKey(
        FairdyUser,
        on_delete=models.SET_NULL,
        null=True
    )
    view_count = models.PositiveIntegerField(default=0, blank=True)

    # returns the URL for the sim's visualize page
    def get_absolute_url(self):
        return '/fairdy/visualize/?id={}'.format(self.id)

    # defines a short string with the sim's parameters
    # for example RS(16,16) or (32,8)-GPC H:{4,6} V:{2,3}
    def __str__(self):
        if self.code_type == self.Codes.REED_SOLOMON:
            return 'RS({},{}), p_error={}'.format(self.k_value, self.m_value, self.p_error)
        elif self.code_type == self.Codes.GENERALIZED_PYRAMID:
            return '({},{})-GPC H:{{{},{}}} V:{{{},{}}}, p_error={}'.format(
                self.n_value,
                self.k_value,
                self.pyramidsimulation.k_horizontal,
                self.pyramidsimulation.m_horizontal,
                self.pyramidsimulation.k_vertical,
                self.pyramidsimulation.m_vertical,
                self.p_error
            )
        elif self.code_type == self.Codes.REPLICATION:
            return 'REP {} copies, p_error={}'.format(self.m_value, self.p_error)
        else:
            self.__str__()

    # returns the number of blocks in the system
    def num_blocks_in_system(self):
        return self.n_value * self.num_stripes

    # returns the number of block cycle credits required for this simulation
    def get_bcc(self):
        return self.num_blocks_in_system() * self.num_cycles

    def get_thumbnail(self):
        max_cycle_count = self.num_cycles + 1
        y = self.cycle_set.values_list('block_availability_factor', flat=True)
        if len(y) < max_cycle_count:
            y = list(y) + ([None] * (max_cycle_count - len(y)))
        x = range(0, max_cycle_count)
        pyplot.plot(x, y, linewidth=7)
        pyplot.xlim(0, max_cycle_count - 1)
        pyplot.ylim(0, 1.1)
        buf = BytesIO()
        pyplot.savefig(buf, format='png', dpi=20)
        pyplot.close()
        return base64.b64encode(buf.getvalue()).decode('utf-8').replace('\n', '')

    def increment_view_count(self):
        self.view_count += 1
        self.save()


class Cycle(models.Model):
    simulation = models.ForeignKey(Simulation, on_delete=models.CASCADE)
    block_availability_factor = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(1)])
    num_faulted_blocks = models.PositiveIntegerField(null=True)
    num_repaired_blocks = models.PositiveIntegerField(null=True)


class PyramidSimulation(models.Model):
    simulation = models.OneToOneField(Simulation, on_delete=models.CASCADE)
    num_repair_cycles = models.IntegerField(
        'Repair Steps per Cycle',
        choices=[(1, 1), (2, 2), (3, 3)],
        default=2
    )
    k_horizontal = models.PositiveIntegerField(
        '(k_horizontal) data',
    )
    m_horizontal = models.PositiveIntegerField(
        '(m_horizontal) redundancy',
    )
    k_vertical = models.PositiveIntegerField(
        '(k_vertical) data',
    )
    m_vertical = models.PositiveIntegerField(
        '(m_vertical) redundancy',
    )
    lazy_heal_threshold_ver = models.PositiveIntegerField(
        default=1,  # default '1' for for eager heal
        validators=[MinValueValidator(1)]
    )

web/fairdy/forms.py
from django import forms

from fairdy.models import Simulation, PyramidSimulation


class SimulationForm(forms.ModelForm):
    class Meta:
        model = Simulation
        fields = ['code_type', 'k_value', 'm_value', 'n_value',
                  'num_stripes', 'num_cycles', 'p_error',
                  'storage_location_mode', 'num_storage_locations', 'lazy_heal_threshold']

    def clean(self):
        cleaned_data = super().clean()
        m_val = cleaned_data.get("m_value")
        k_val = cleaned_data.get("k_value")
        n_val = cleaned_data.get("n_value")
        if n_val != k_val + m_val:
            raise forms.ValidationError(
                "Check stripe configuration, the sum of redundancy and data "
                "blocks does not equal the total number of blocks."
            )


class PyramidSimulationForm(forms.ModelForm):
    class Meta:
        model = PyramidSimulation
        fields = ['num_repair_cycles', 'k_horizontal', 'm_horizontal',
                  'k_vertical', 'm_vertical', 'lazy_heal_threshold_ver']

web/fairdy/views.py
import base64
import csv
from io import BytesIO

import fairdypy
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Max
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from matplotlib import pyplot

from accounts.models import FairdyUser
from fairdy.forms import SimulationForm, PyramidSimulationForm
from fairdy.models import Simulation, Cycle
from web import settings


def index(request, code_type=None):
    # If code type parameter is not None (meaning show sims for all codes)
    # Check it is a valid installed code, and set the request's code_type
    if code_type is not None:
        installed_codes = [item.name for item in Simulation.Codes]
        code_type = code_type.upper()
        if code_type not in installed_codes:
            raise Http404()
        else:
            # get sim list from database filtered by the valid code
            request.code_type = Simulation.Codes[code_type]
            sim_list = Simulation.objects.filter(code_type=request.code_type)
    else:
        sim_list = Simulation.objects.all()
        # filter the sim list from database by username if present in the query string
        if 'username' in request.GET:
            fairdy_user = FairdyUser.objects.get(user__username=request.GET['username'])
            sim_list = sim_list.filter(fairdy_user=fairdy_user)

    # Django paginator initialization
    paginator = Paginator(sim_list.order_by('-id'), 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'index.html', {'page_obj': page_obj})


def about(request):
    return render(request, 'about.html')


def about_simulation(request):
    return render(request, 'help/templates/about_simulation.html')


# Helper method to instantiate the different codes in the fairdy module
# If new codes are added to web app, this function must be updated,
# together with Simulation.Codes and Simulation.__str__
def run_module_simulation(web_sim):
    # STANDARD CODES
    standard_codes = [Simulation.Codes.REED_SOLOMON, Simulation.Codes.REPLICATION]
    if web_sim.code_type in standard_codes:
        module_sim = fairdypy.Reed_solomon(
            word_blocks=web_sim.k_value,
            extra_blocks=web_sim.m_value,
            num_of_stripes=web_sim.num_stripes,
            lazy_heal_threshold=web_sim.lazy_heal_threshold,
            storage_fault_mode=web_sim.storage_location_mode,
            num_of_storage=web_sim.num_storage_locations if web_sim.storage_location_mode else None,
        )

    # GENERALIZED PYRAMID
    elif web_sim.code_type == Simulation.Codes.GENERALIZED_PYRAMID:
        module_sim = fairdypy.Generalized_pyramid_code(
            gpc_definition=(web_sim.n_value, web_sim.k_value),
            horizontal_rs=(web_sim.pyramidsimulation.k_horizontal, web_sim.pyramidsimulation.m_horizontal),
            vertical_rs=(web_sim.pyramidsimulation.k_vertical, web_sim.pyramidsimulation.m_vertical),
            num_of_stripes=web_sim.num_stripes,
            lazy_heal_threshold_hor=web_sim.lazy_heal_threshold,
            lazy_heal_threshold_vert=web_sim.pyramidsimulation.lazy_heal_threshold_ver,
            storage_fault_mode=web_sim.storage_location_mode,
            num_of_storage=web_sim.num_storage_locations if web_sim.storage_location_mode else None,
            repair_cycle=web_sim.pyramidsimulation.num_repair_cycles
        )
    # RUN SIMULATION
    module_sim.loop_simulation(
        loops=web_sim.num_cycles,
        p_error=web_sim.p_error,
    )
    return module_sim


# helper method to redirect if accounts app is enabled, and the user is not logged in
def is_valid_user(request):
    if settings.USE_ACCOUNTS_APP:
        if request.user.is_anonymous:
            messages.error(request, 'You must log in before running simulations.')
            return False
        else:
            fairdy_user = FairdyUser.objects.get(user_id=request.user.id)
            if settings.REQUIRE_EMAIL_VERIFICATION and not fairdy_user.is_valid_email:
                messages.error(request, 'You must validate your email before running simulations.')
                return False
    return True


def user_has_enough_bcc(web_sim):
    # if the accounts app is turned off, ignore null fairdy_user
    if not web_sim.fairdy_user:
        if not settings.USE_ACCOUNTS_APP:
            return True
        else:
            return False
    # Check user has enough block cycle credits available to run this simulation
    elif settings.USE_ACCOUNTS_APP and settings.ENFORCE_BLOCK_CYCLE_LIMIT \
            and web_sim.fairdy_user.can_run_simulation(web_sim):
        return True
    else:
        return False


def initialize_gp(web_sim, gpc_form):
    if gpc_form.is_valid():
        web_sim.save()
        gpc_sim = gpc_form.save(commit=False)
        gpc_sim.simulation = web_sim
        gpc_sim.save()
        return True
    else:
        return False


def run_simulation(request):
    if not is_valid_user(request):
        return redirect('fairdy:index')

    if request.method == 'POST':
        sim_form = SimulationForm(request.POST)
        gpc_form = PyramidSimulationForm(request.POST)

        if sim_form.is_valid():
            web_sim = sim_form.save(commit=False)
            web_sim.fairdy_user = FairdyUser.objects.get(user_id=request.user.id) if request.user.is_authenticated else None
            web_sim.start_time = timezone.now()

            # check the user has enough credits to run the sim, or is exempt
            if not user_has_enough_bcc(web_sim):
                messages.error(request, 'You do not have enough block cycle credits to run this simulation, '
                                        'ask the administrator to raise your limit.')
                return redirect('fairdy:index')

            # deal with extra fields required by pyramid codes
            if web_sim.code_type == Simulation.Codes.GENERALIZED_PYRAMID and not initialize_gp(web_sim, gpc_form):
                messages.error(request, gpc_form.non_field_errors())
                return render(request, 'form.html', {'base_form': sim_form, 'gpc_form': gpc_form})

            # try running simulation
            try:
                module_sim = run_module_simulation(web_sim)
                if len(module_sim.baf_history) is 0:
                    messages.error(request, 'There was a problem running the simulation')
                    return render(request, 'form.html', {'base_form': sim_form, 'gpc_form': gpc_form})
                web_sim.save()
                cycles = (Cycle(
                        simulation=web_sim,
                        block_availability_factor=module_sim.baf_history[cycle],
                        num_faulted_blocks=module_sim.blocks_died_history[cycle],
                        num_repaired_blocks=module_sim.blocks_healed_history[cycle]
                    ) for cycle in range(len(module_sim.baf_history))
                )
                Cycle.objects.bulk_create(cycles)
                web_sim.end_time = timezone.now()
                web_sim.save()
                return redirect(web_sim)

            except ValueError as error:
                if web_sim:
                    web_sim.delete()
                messages.error(request, error)
        else:
            messages.error(request, "There was an error with the stripe parameters you entered.")

    else:    # = request.method is NOT POST
        sim_form = SimulationForm()
        # prefill the code-type on the form if the user clicked from a specific code page
        if 'code_type' in request.GET:
            sim_form.initial = {'code_type': request.GET['code_type']}
        gpc_form = PyramidSimulationForm()
    return render(request, 'form.html', {'sim_form': sim_form, 'gpc_form': gpc_form})


def get_csv(request):
    if 'id' not in request.GET:
        raise Http404()
    ids = request.GET.getlist('id')

    sim_fields = ['id', 'code_type', 'n_value', 'k_value', 'm_value', 'num_stripes', 'num_cycles', 'p_error',
                  'lazy_heal_threshold', 'storage_location_mode', 'num_storage_locations']
    gpc_fields = ['k_horizontal', 'm_horizontal', 'k_vertical', 'm_vertical', 'lazy_heal_threshold_ver',
                  'num_repair_cycles']
    sims = Simulation.objects.filter(pk__in=ids).order_by('-id')
    # set maximum number of cycles to the highest that any of the selected sims have
    max_cycle_count = sims.aggregate(Max('num_cycles'))['num_cycles__max'] + 1

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="FaiRDy.csv"'
    writer = csv.writer(response)
    cycle_fields = list('cycle {}'.format(i) for i in range(max_cycle_count))
    writer.writerow(sim_fields + gpc_fields + cycle_fields)
    for sim in sims:
        writer.writerow(
            list(getattr(sim, field) for field in sim_fields) +
            list(getattr(sim.pyramidsimulation, field) if hasattr(sim, 'pyramidsimulation') else '' for field in gpc_fields) +
            list(getattr(cycle, 'block_availability_factor') for cycle in sim.cycle_set.all())
        )
        writer.writerow(
            ['faulted_blocks'] +
            list('' for i in range(len(sim_fields + gpc_fields)-1)) +
            list(getattr(cycle, 'num_faulted_blocks') for cycle in sim.cycle_set.all())
        )
        writer.writerow(
            ['healed_blocks'] +
            list('' for i in range(len(sim_fields + gpc_fields)-1)) +
            list(getattr(cycle, 'num_repaired_blocks') for cycle in sim.cycle_set.all())
        )

    return response


def visualize(request):
    if 'id' not in request.GET:
        raise Http404()
    ids = request.GET.getlist('id')
    sims = Simulation.objects.filter(pk__in=ids).order_by('-id')
    # increment the view count on each of the simulations
    for sim in sims:

web/fairdy/templates/index.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

    <script>
    $(document).ready(function () {
        let url = new URL(window.location.href);
        let params = url.searchParams;
        let id_list = params.getAll('id');

        //when first loading the page, recheck all the check boxes that are stored in the query dict
        replace_checks(id_list);
        update_id_list(id_list);
        refresh_buttons(id_list);

        //anytime a checkbox's state is changed, the 'id_list' variable in this page's javascript is updated
        $('input:checkbox').change(function() {
            update_id_list(id_list);
        });

        //when a link is clicked to another pagination page, first update the link's query dict with any
        // changes made to checkboxes and also the username if necessary
        $('.page-link').click(function() {
            update_href($(this), params, id_list);
        });

        //when the compare button is clicked, update the link with the collected ids before following it
        $('#compare_button').click(function () {
            update_href($(this), params, id_list);
        });

        //when the download button is clicked, update the link with the collected ids before following it
        $('#download_button').click(function () {
            update_href($(this), params, id_list);
        });

    });


    //recheck the simulations that have been stored in the query dict when revisiting the page they are on
    function replace_checks(id_list) {
        $('input:checkbox').each(function () {
            let id = $(this).attr('id').replace('checkboxid_', '');
            if (id_list.includes(id)) {
                $(this).attr('checked', true);
            }
        });
    }

    //toggles the state of the compare and download buttons when enough simulations are selected
    function refresh_buttons(id_list) {
        //(de)activate the buttons
        if (id_list.length > 1) {
            $('#compare_button').removeClass('disabled');
        } else {
            $('#compare_button').addClass('disabled');
        }
        if (id_list.length > 0) {
            $('#download_button').removeClass('disabled');
        } else {
            $('#download_button').addClass('disabled');
        }
    }

    //function to update the id_list stored in memory based on what was
    //checked or unchecked on the currently display page
    function update_id_list(id_list) {

        //look at the checkboxes that are checked
        $("input:checkbox:checked").each(function() {
            let id = $(this).attr('id').replace('checkboxid_', '');
            if (!id_list.includes(id)) {
                id_list.push(id);
            }
        });

        //look at the checkboxes that are unchecked
        $("input:checkbox:not(:checked)").each(function() {
            let id = $(this).attr('id').replace('checkboxid_', '');
            if (id_list.includes(id)) {
                let index = id_list.indexOf(id);
                if (index > -1) {
                    id_list.splice(index, 1);
                }
            }
        });
        refresh_buttons(id_list);

    }

    //delete all ids in the query dict and replace them with the updated list
    //there was no good way to delete invidual ids out of the query dict
    function update_href(element, params, id_list) {
        let link = element.attr("href");

        if (element.attr('id')=='compare_button' || element.attr('id')=='download_button') {
            link = link.split('?')[0] += '?'
            params.delete('username')
        } else if (id_list.length > 0 || params.has('username')) {
            link += '&'
        }

        params.delete('id');
        params.delete('page');

        id_list.forEach(function (item, index) {
            params.append('id', item);
        });

        link += params.toString();
        element.attr("href", link);
    }
    </script>

    <div class="row">
        <div class="col">
                <div class="card">
        <!--CARD HEADER-->
        <div class="card-header">
            <h4 class="card-title float-left">Simulations of Storage System Life Cycles</h4>
            <a class="btn btn-primary float-right" href="{% url 'fairdy:run_simulation' %}{% if request.code_type %}?code_type={{ request.code_type }}{% endif %}">New</a>
        </div>

        <!--CARD BODY-->
        <div class="card-body">
            <h5 class="card-subtitle text-muted">
                {% if 'username' in request.GET %}
                    showing systems ran by {{ request.GET.username }}
                {% elif not request.code_type %}
                    showing systems using using all erasure codes
                {% else %}
                    showing systems using {{ request.code_type.label}} erasure codes
                {% endif %}
            </h5>
            {% with sims=page_obj %}
            {% include 'list.html' %}
            {% endwith %}



                                <nav class="d-flex justify-content-center">
                <ul class="pagination m-0 ">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}

                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page_obj.number }}</a>
                    </li>


                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>



        </div>
        <!--CARD FOOTER-->
        <div class="card-footer">
            <span class="float-left" style="font-size: 1.5em">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            <div class="btn-group float-right">
                <a class="btn btn-primary disabled" href="{% url 'fairdy:get_csv' %}" id="download_button">Download</a>
                <a class="btn btn-primary disabled" href="{% url 'fairdy:visualize' %}" id="compare_button">Compare</a>
            </div>
        </div>
    </div>



        </div>
    </div>
{% endblock %}

web/fairdy/templates/list.html
{% block content %}
    <style>
        .internal_table {
            border-collapse: collapse;
            padding: 0;
        }
        .internal_table tr td, .internal_table tr th {
            border: 0;
        }
        td.internal_cell {
            padding: 0;
        }
    </style>


    <table class="table table-sm table-bordered">
        <thead>
        <tr>
                <th>storage system</th>
                <th>curve</th>
                <th>blocks in stripe</th>
                <th>system dimension</th>
                <th>options</th>
                <th>details</th>
            </tr>

        </thead>
        <tbody>
        {% for simulation in sims %}
            <tr>
                <!--STORAGE SYSTEM COLUMN-->
                <td class="internal_cell">
                    <table class="internal_table">
                        <tr><td><input type="checkbox" id="checkboxid_{{ simulation.id }}"> {{ simulation }}</td></tr>
                        <tr><td><a href="{% url 'fairdy:visualize' %}?id={{ simulation.id }}">view sim{{ simulation.id }}</a></td></tr>
                    </table>

                </td>
                <!--THUMBNAIL COLUMN-->
                <td>
                    <img src="data:image/png;base64,{{ simulation.get_thumbnail }}" class="img-fluid p-0">
                </td>
                <!--BLOCKS PER STRIPE-->
                <td class="internal_cell">
                    <table class="internal_table">
                        <tr><td>{{ simulation.k_value }}</td><td><small class="text-muted">data</small></td></tr>
                        <tr><td>{{ simulation.m_value }}</td><td><small class="text-muted">redundancy</small></td></tr>
                        <tr style="border-top: 1px solid gray"><td>{{ simulation.n_value }}</td><td><small class="text-muted">total</small></td></tr>
                    </table>
                </td>
                <!--SYSTEM SIZE COLUMN-->
                <td class="internal_cell">
                    <table class="internal_table">
                        <tr><td>{{ simulation.num_cycles }}</td><td><small class="text-muted">cycles</small></td></tr>
                        <tr style="border-top: 1px solid gray"><td>{{ simulation.num_stripes }}</td><td><small class="text-muted">stripes</small></td></tr>
                        <tr><td>{{ simulation.num_blocks_in_system }}</td><td><small class="text-muted">blocks</small></td></tr>
                        <tr></tr>
                    </table>
                </td>
                <!--OPTIONS COLUMN-->
                <td class="internal_cell">
                    <table class="internal_table">
                        {% if simulation.storage_location_mode is not None %}
                        <tr><th>storage mode</th><td>{{ simulation.storage_location_mode }}</td></tr>
                        {% endif %}
                        {% if simulation.num_storage_locations != simulation.num_blocks_in_system %}
                        <tr><th>storage locations</th><td>{{ simulation.num_storage_locations }}</td></tr>
                        {% endif %}
                        {% if simulation.lazy_heal_threshold != 1 %}
                        <tr><th>lazy heal threshold (horizontal)</th><td>{{ simulation.lazy_heal_threshold }}</td></tr>
                        {% endif %}
                        {% if simulation.pyramidsimulation and simulation.pyramidsimulation.lazy_heal_threshold_ver != 1 %}
                        <tr><th>lazy heal threshold (vertical)</th><td>{{ simulation.pyramidsimulation.lazy_heal_threshold_ver }}</td></tr>
                        {% endif %}
                        {% if simulation.pyramidsimulation %}
                        <tr><th>repair cycles</th><td>{{ simulation.pyramidsimulation.num_repair_cycles }}</td></tr>
                        {% endif %}
                    </table>
                </td>
                <td class="internal_cell">
                    <table class="internal_table">
                        {% with username=simulation.fairdy_user.user.username %}
                        <td><a href="{% url 'fairdy:index' %}?username={{ username }}">{{ username }}</a></td>
                        {% endwith %}
                        <tr><td>{{ simulation.end_time|date:"d-M-Y" }}</td></tr>
                        <tr><td>{{ simulation.view_count }} views</td></tr>
                    </table>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

web/fairdy/templates/visualize.html
{% extends "base.html" %}

{% block content %}
    <style>
        input[type="checkbox"] {
            display:none;
        }
    </style>

    <div class="row">
        <div class="justify-content-center">
            <img src="data:image/png;base64,{{ graph }}" class="img-fluid">
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include 'list.html' %}
        </div>
    </div>

{% endblock %}