web/accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('user_index/', user_index, name='user_index'),
    path('user_edit/', user_edit, name='user_edit'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('change_username/', change_username, name='change_username'),
    path('change_email/', change_email, name='change_email'),
    path('change_password/', change_password, name='change_password'),
    path('reset_password/<token>/', reset_password, name='reset_password'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('delete/', delete, name='delete'),
    path('profile/', profile, name='profile'),
    path('validate/<token>/', validate_email, name='validate'),
    path('resend_validation', resend_validation, name='resend_validation'),
    path('help/create_account/', help_create_account, name='help_create_account'),
    path('help/manage_account/', help_manage_account, name='help_manage_account'),
    path('help/manage_users/', help_manage_users, name='help_manage_users'),
]

web/fairdy/urls.py
from django.urls import path

from .views import *

app_name = 'fairdy'

urlpatterns = [
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('visualize/', visualize, name='visualize'),
    path('run/', run_simulation, name='run_simulation'),
    path('csv/', get_csv, name='get_csv'),
    path('about_simulation/', about_simulation, name='about_simulation'),
    path('help/getting_started/', help_getting_started, name='help_getting_started'),
    path('help/run_simulation/', help_run_simulation, name='help_run_simulation'),
    path('help/compare_download/', help_compare_download, name='help_compare_download'),
    # should be last since it will check any string (after /fairdy/) to see if it is an installed code
    path('<str:code_type>/', index, name='codes'),
]

web/web/urls.py
from django.urls import path, include

from fairdy.views import *

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('accounts/', include('accounts.urls')),
    path('fairdy/', include('fairdy.urls')),
]

web/accounts/forms.py
from django import forms
from django.contrib.auth import validators
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FairdyRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self:
            # Add Bootstrap classes to all the form's elements except the 'agree to conditions' checkbox
            if field.name != 'agree_to_conditions':
                field.field.widget.attrs.update({'class': 'form-control'})
                field.field.widget.attrs.update({'placeholder': field.label})

        self.fields['username'].widget.attrs.update({'autofocus': False})
        self.fields['email'].widget.attrs.update({'autofocus': True})

    email = forms.EmailField(max_length=254, help_text='You must enter a valid email address.')
    agree_to_conditions = forms.BooleanField(required=True, widget=forms.CheckboxInput, label='I agree to the terms and conditions above.')

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class ChangeUsernameForm(forms.Form):
    username = forms.CharField(required=True, validators={validators.UnicodeUsernameValidator}, label='New Username')


class ChangeEmailForm(forms.Form):
    email = forms.EmailField(required=True, label='New Email Address')


class DeleteUserForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)


class ChangePasswordForm(forms.Form):
    password_old = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)


class ResetPasswordForm(forms.Form):
    user_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)


class ForgotPasswordForm(forms.Form):
    username = forms.CharField(required=True)


class AdminEditUserForm(forms.Form):
    user_id = forms.IntegerField()
    block_cycle_limit = forms.IntegerField()
    is_staff = forms.BooleanField(required=False)

web/accounts/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import logout_then_login
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from .forms import FairdyRegistrationForm, DeleteUserForm, ForgotPasswordForm, ChangePasswordForm, ResetPasswordForm, \
    ChangeUsernameForm, ChangeEmailForm, AdminEditUserForm
from .models import FairdyUser


# VALIDATE EMAIL
def validate_email(request, token):
    fairdy_user = get_object_or_404(FairdyUser, token=token)

    # token must not be reused
    if fairdy_user.is_valid_email:
        raise Http404

    # token must not be expired
    if fairdy_user.token_is_expired():
        fairdy_user.send_validation_email()
        messages.error(request, "Sorry! It looks like that link had already expired, "
                                "please check your email for a new one.")
        return redirect('fairdy:index')

    login(request, fairdy_user.user)
    fairdy_user.is_valid_email = True
    fairdy_user.save()
    messages.success(request, "Email successfully validated!")
    return redirect('accounts:profile')


# RESET PASSWORD
# allows user to enter a new password if they have the correct token from their email
def reset_password(request, token):
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            fairdy_user = get_object_or_404(FairdyUser, user_id=form.cleaned_data['fairdy_user'])

            # token must not be reused
            if not fairdy_user.is_password_expired:
                raise Http404

            # token must not be expired
            if fairdy_user.token_is_expired():
                fairdy_user.send_validation_email()
                messages.error(request, "Sorry! It looks like that link had already expired, "
                                        "please check your email for a new one.")
                return redirect('fairdy:index')

            pw1 = form.cleaned_data['password1']
            pw2 = form.cleaned_data['password2']
            if token == fairdy_user.token and pw1 == pw2:
                fairdy_user.user.set_password(pw1)
                fairdy_user.user.save()
                fairdy_user.is_password_expired = False
                fairdy_user.save()
                login(request, fairdy_user.user)
                messages.success(request, 'Password successfully changed.')
                return redirect('accounts:profile')

    form = ResetPasswordForm({'user_id': get_object_or_404(FairdyUser, token=token).user_id})
    return render(request, 'password_reset.html', {'form': form})


# FORGOT PASSWORD
# sends password reset email and deactivates user, if the username is found
def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            try:
                fairdy_user = FairdyUser.objects.get(user_id=User.objects.get(username=form.cleaned_data["username"]))
                fairdy_user.fairdy_user.set_unusable_password()
                fairdy_user.is_password_expired = True
                messages.success(request, 'Password is reset. Check your email for a link to set a new one.')
                fairdy_user.send_reset_email()
                return redirect('fairdy:index')
            except ObjectDoesNotExist:
                messages.error(request, 'User not found.')
    return render(request, 'password_forgot.html')


# REGISTER
# register a new account, and send a confirmation email
def register(request):
    if request.method == 'POST':
        form = FairdyRegistrationForm(request.POST)
        if form.is_valid():
            username = form.save()
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            fairdy_user = FairdyUser.objects.create_fairdy_user(user)
            fairdy_user.send_validation_email()
            messages.success(request, 'Thank you for registering an account on fairdy.no! '
                                      'Follow the link in your email to complete the process.')
            return redirect('accounts:profile')
    else:
        form = FairdyRegistrationForm()
    return render(request, 'register.html', {'form': form})

# LOG OUT
@login_required
def logout(request):
    messages.success(request, 'Successfully logged out.')
    return logout_then_login(request)


# PROFILE
# return the main profile page for the currently logged in user
@login_required
def profile(request):
    return render(request, 'profile.html')


# CHANGE USERNAME
# allows a logged in user to update their username, as long as the username they want is not already taken
@login_required
def change_username(request):
    if request.method == 'POST':
        form = ChangeUsernameForm(request.POST)
        if form.is_valid():
            user = request.user
            user.username = form.cleaned_data['username']
            try:
                user.save()
                messages.success(request, 'Your username was successfully updated.')
            except IntegrityError:
                messages.error(request, 'That username is not available, please try something else.')
            return redirect('accounts:profile')
    return render(request, 'update.html', {'form': ChangeUsernameForm()})


# CHANGE EMAIL
# allows a logged in user to update their email, it will be necessary to validate the new email
# it is possible for multiple user accounts to have the same email registered and validated
@login_required
def change_email(request):
    if request.method == 'POST':
        form = ChangeEmailForm(request.POST)
        if form.is_valid():
            user = request.user
            user.email = form.cleaned_data['email']
            user.save()
            fairdy_user = FairdyUser.objects.get(user_id=user.id)
            fairdy_user.is_valid_email = False
            fairdy_user.send_validation_email()
            messages.success(request, 'Your email address was successfully updated. '
                                      'Follow the link in your email to complete the process.')
            return redirect('accounts:profile')
        messages.error(request, 'There was a problem updating your email address.')
    return render(request, 'update.html', {'form': ChangeEmailForm()})


# CHANGE PASSWORD
# allows a logged in user to update their password, correct current password is required
@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            pw1 = form.cleaned_data['password1']
            pw2 = form.cleaned_data['password2']
            pw_old = form.cleaned_data['password_old']
            user = request.user
            if user.check_password(pw_old) and pw1 == pw2 and pw1 != pw_old:
                user.set_password(pw1)
                user.save()
                alert = 'Your password was successfully changed.'
                messages.add_message(request, messages.SUCCESS, alert)
                return redirect('accounts:profile')
        messages.success(request, 'There was a problem changing your password. Please try again.')
    return render(request, 'password_change.html', {'form': ChangePasswordForm()})


# RESEND VALIDATION EMAIL
@login_required
def resend_validation(request):
    fairdy_user = FairdyUser.objects.get(user_id=request.user.id)
    # Only validate the email address for a user once
    if fairdy_user.is_valid_email:
        raise Http404
    else:
        fairdy_user.send_validation_email()
        messages.success(request, "A new validation link was sent to your email.")
        return redirect('accounts:profile')


# DELETE THE ACCOUNT
# Delete the account of the currently logged in user, if they provide their correct password
@login_required
def delete(request):
    if request.method == 'POST':
        form = DeleteUserForm(request.POST)
        if form.is_valid():
            user = authenticate(username=request.user, password=form.cleaned_data.get('password'))
            if user is not None:
                # TODO delete simulations also?
                logout(request)
                user.delete()
                messages.success(request, 'Account deleted successfully.')
            else:
                messages.error(request, 'Error deleting account. Check your password and try again')
            return render(request, 'index.html')

    return render(request, 'delete.html', {'form': DeleteUserForm()})


# USER ACCOUNT ADMINISTRATION
# view index of all user accounts registered in the database
@staff_member_required
def user_index(request):
    user_list = FairdyUser.objects.all().order_by('user__username')
    paginator = Paginator(user_list, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'user_index.html', {'page_obj': page_obj})


# EDIT USER ACCOUNT
# edit a user account in the database, only available as post, request comes from user_index page
@staff_member_required
def user_edit(request):
    form = AdminEditUserForm(request.POST)
    if form.is_valid():
        fairdy_user = get_object_or_404(FairdyUser, user_id=form.cleaned_data['user_id'])
        if form.cleaned_data['is_staff']:
            fairdy_user.user.is_staff = True
            fairdy_user.block_cycle_limit = -1
        else:
            fairdy_user.user.is_staff = False
            fairdy_user.set_bcl_millions(form.cleaned_data['block_cycle_limit'])

web/accounts/templates/delete.html
{% extends "base.html" %}
{% block title %}Delete Account{% endblock %}

{% block content %}
    <div class="col-xl-6 col-lg-8">
        <div>
            <h4>Are you sure you want to delete your account on fairdy.no?</h4>
            <p>
                We will remove your email and username from our database.
            </p>
            <p>
                The simulations you have run will remain in our database,
                however they will no longer be associated with your account details.
            </p>
            <p>
                Please enter your password and click confirm if you wish to continue.
            </p>
            <form method="post" action="{% url 'accounts:delete' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="password" name="password" id="password">
                </div>
                <div class="form-group text-right">
                    <a class="btn btn-primary" href="{% url 'accounts:profile' %}">Cancel</a>
                    <input type="submit" class="btn btn-danger" value="Confirm">
                </div>

            </form>
        </div>
    </div>
{% endblock %}

web/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}


<div class="col-xl-4 col-lg-6 col-md-8">
    <div class="card">
        <div class="card-header">
            Log in
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" autofocus type="text" name="username" id="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                </div>
                {% if form.errors %}
                    <p class="form-text" style="color:red">
                        Your username and password didn't match. Please try again.
                    </p>
                {% endif %}
                <button type="submit" class="btn btn-primary">Submit</button>
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </div>
        <div class="card-body">
            <a class="card-link" href="{% url 'accounts:forgot_password' %}">Forgot password?</a>
            <a class="card-link" href="{% url 'accounts:register' %}">Register?</a>
        </div>

    </div>
</div>

{% endblock %}

web/accounts/templates/password_change.html
{% extends "base.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}

    <div class="col-xl-4 col-lg-6 col-md-8">
        <div class="card">
            <div class="card-header">
                Change Password
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'accounts:change_password' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="password" name="password_old" id="password_old" placeholder="Current Password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password1" id="password1" placeholder="New Password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password2" id="password2" placeholder="New Password Confirmation">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

web/accounts/templates/password_forgot.html
{% extends "base.html" %}

{% block title %}Forgot Password{% endblock %}

{% block content %}

    <div class="col-xl-4 col-lg-6 col-md-8">
        <div class="card">
            <div class="card-header">
                Forgot Password
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'accounts:forgot_password' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="form-text" for="username">Enter your username below, and follow the link in your email to reset your password.</label>
                        <input class="form-control" autofocus type="text" name="username" id="username" placeholder="Username">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="card-body">
                <a class="card-link" href="{% url 'accounts:register' %}">Register?</a>
                <a class="card-link" href="{% url 'accounts:login' %}">Log in?</a>
            </div>
        </div>
    </div>

{% endblock %}

web/accounts/templates/password_reset.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}


<div class="card">
    <div class="card-header">
        Reset Password
    </div>
    <div class="card-body">
        <form method="post" action="{{ request.path }}">
            {% csrf_token %}
            {{ form.user_id }}
            <div class="form-group">
                <input class="form-control" type="password" name="password1" id="password1" placeholder="New Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password2" id="password2" placeholder="New Password Confirmation">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>

{% endblock %}

web/accounts/templates/profile.html
{% extends "base.html" %}
{% load accounts_extras %}
{% block title %}Profile{% endblock %}

{% block content %}

    <div class="col-xl-6 col-lg-8">
        <table class="table table-sm">
        <tbody>
            <tr>
                <th>Username</th>
                <td>{{ user.username }} <a class="float-right" href="{% url 'accounts:change_username' %}">update</a> </td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }} <a class="float-right" href="{% url 'accounts:change_email' %}">update</a></td>
            </tr>
            <tr>
                <th>Remaining Credits</th>
                <td>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: {{ user.fairdyuser.get_remaining_bcc_percent }}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </td>
            </tr>
            {% if user|is_email_verified %}
                <tr><th class="table-success" colspan="2">Email is verified.</th> </tr>
            {% else %}
                <tr><td class="table-danger" colspan="2">Email is not verified.<a class="float-right" href="{% url 'accounts:resend_validation' %}">resend confirmation</a></td> </tr>
            {% endif %}
            <tr>
                <th>Last Login</th>
                <td>{{ user.last_login|date:"d-M-Y H:i" }}</td>
            </tr>
            <tr>
                <th>Joined</th>
                <td>{{ user.date_joined|date:"d-M-Y H:i" }}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <ul style="list-style-type: none; padding-left: 0;">
                        <li><a href="{% url 'fairdy:index' %}?username={{ user.username }}">My Simulations</a></li>
                        <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                        <li><a href="{% url 'accounts:delete' %}">Delete Account</a></li>
                    </ul>
                </td>
            </tr>
        </tbody>
        </table>
    </div>


{% endblock %}

web/accounts/templates/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
    <div class="col-xl-4 col-lg-6 col-md-8">
        <div class="card">
            <div class="card-header">
                Register
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'accounts:register' %}">


                    {% csrf_token %}

                    {% for field in form %}
                        {% if field.name == 'agree_to_conditions' %}
                            <div class="form-group">
                                Terms and Conditions:
                                <ul class="list-group">
                                    <li class="list-group-item">This website uses cookies to optimize user experience by storing information about your session.</li>
                                    <li class="list-group-item">This website will store your username and email, as well as timestamps associated with registration, login, use, etc.</li>
                                    <li class="list-group-item">We will never share your email or other personal information with any third parties.</li>
                                    <li class="list-group-item">The simulations you run will be publicly visible with the username you choose, your email will not be shared publicly.</li>
                                    <li class="list-group-item">You may delete your account at any time by going to your profile and following the 'Delete Account' link.</li>
                                    <li class="list-group-item">After you delete your account, all simulations you have run will remain in our database, but without any reference to your former account or personal data.</li>
                                </ul>
                            </div>
                            <div class="form-group">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" name="{{ field.html_name }}">
                                    <label class="form-check-label" for="{{ field.html_name }}">{{ field.label }}</label>
                                </div>
                            </div>

                        {% else %}
                            <div class="form-group">
                                {{ field }}
                            </div>
                        {% endif %}

                        {% for error in field.errors %}
                            <p class="form-text" style="color: red">{{ error }}</p>
                        {% endfor %}
                        {% if field.help_text and field.errors %}
                            <p class="form-text" style="color: grey">{{ field.help_text }}</p>
                        {% endif %}
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>

                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
            <div class="card-body">
                <a class="card-link" href="{% url 'accounts:forgot_password' %}">Forgot password?</a>
                <a class="card-link" href="{% url 'accounts:login' %}">Log in?</a>
            </div>
        </div>
    </div>
    <script>
        $(':checkbox').change(function(){
            cb = $(this);
            if (cb.prop('checked')) {
                cb.val(true);
            }

        });
    </script>

{% endblock %}

web/accounts/templates/update.html
{% extends "base.html" %}

{% block title %}Update Profile{% endblock %}

{% block content %}

    <div class="col-xl-4 col-lg-6 col-md-8">
        <div class="card">
            <div class="card-header">
                Update Profile
            </div>
            <div class="card-body">
                <form method="post" action="{{ request.path }}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% for error in field.errors %}
                            <p class="form-text" style="color: red">{{ error }}</p>
                        {% endfor %}
                        {% if field.help_text and field.errors %}
                            <p class="form-text" style="color: grey">{{ field.help_text }}</p>
                        {% endif %}
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}