web/accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('user_index/', user_index, name='user_index'),
    path('user_edit/', user_edit, name='user_edit'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('change_username/', change_username, name='change_username'),
    path('change_email/', change_email, name='change_email'),
    path('change_password/', change_password, name='change_password'),
    path('reset_password/<token>/', reset_password, name='reset_password'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('delete/', delete, name='delete'),
    path('profile/', profile, name='profile'),
    path('validate/<token>/', validate_email, name='validate'),
    path('resend_validation', resend_validation, name='resend_validation'),
    path('help/create_account/', help_create_account, name='help_create_account'),
    path('help/manage_account/', help_manage_account, name='help_manage_account'),
    path('help/manage_users/', help_manage_users, name='help_manage_users'),
]

web/fairdy/urls.py
from django.urls import path

from .views import *

app_name = 'fairdy'

urlpatterns = [
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('visualize/', visualize, name='visualize'),
    path('run/', run_simulation, name='run_simulation'),
    path('csv/', get_csv, name='get_csv'),
    path('about_simulation/', about_simulation, name='about_simulation'),
    path('help/getting_started/', help_getting_started, name='help_getting_started'),
    path('help/run_simulation/', help_run_simulation, name='help_run_simulation'),
    path('help/compare_download/', help_compare_download, name='help_compare_download'),
    # should be last since it will check any string (after /fairdy/) to see if it is an installed code
    path('<str:code_type>/', index, name='codes'),
]

web/web/urls.py
from django.urls import path, include

from fairdy.views import *

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('accounts/', include('accounts.urls')),
    path('fairdy/', include('fairdy.urls')),
]

web/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}

{% block content %}
    <div class="col-12">
        <div>
            <h4>About FaiRDy</h4>
            <p>
                The FaiRDy platform was originally envisioned and developed by Veronica Estrada Galiñanes and coded in the Wolfram Language.
            </p>

            <p>
                FaiRDy-Py and fairdy.ux.uis.no were created by Adam Becker and Lars Kartevoll in Spring 2020
                for their exit project in the Bachelor of Computer Science program at the University of Stavanger, Norway.
                The goal of FaiRDy-Py was to create a Python version of FaiRDy with an accompanying web platform.
                The creator of FaiRDy, Veronica Estrada Galiñanes, advised us on our work to implement the framework in Python.
            </p>
            <p>
                Our project is open source, you can download and customize our code on
                <a href="https://github.com/nextgen-codes/fairdy-py">github.com/nextgen-codes/fairdy-py</a>
            </p>

        </div>
    </div>


{% endblock %}

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static '../static/favicon.ico' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <style>
            body {
              padding-top: 5rem;
            }
        </style>

        <script type="text/javascript">
            $(document).ready(function () {

            });
        </script>
        <title>FaiRDy {% block title %}{% endblock %}</title>
    </head>

    <body>
        <!--TOP NAVIGATION BAR-->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href={% url 'fairdy:index' %}>FaiRDy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown">Erasure Codes</a>
                        <div class="dropdown-menu">
                            {% for code in installed_codes %}
                                {% if request.code_type.name == code.name %}
                                    <a class="dropdown-item" href="/fairdy/{{ code.name|lower }}">{{code.label}}</a>
                                {% else %}
                                    <a class="dropdown-item" href="/fairdy/{{ code.name|lower }}">{{code.label}}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown">Documentation</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'fairdy:help_getting_started' %}">Getting Started</a>
                            <a class="dropdown-item" href="{% url 'fairdy:help_run_simulation' %}">Running Simulations</a>
                            <a class="dropdown-item" href="{% url 'fairdy:help_compare_download' %}">Compare and Download</a>
                                      <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:help_create_account' %}">Create Account</a>
                            <a class="dropdown-item" href="{% url 'accounts:help_manage_account' %}">Manage Account</a>
                            {% if request.user.is_staff %}
                            <a class="dropdown-item" href="{% url 'accounts:help_manage_users' %}">Manage Users</a>
                            {% endif %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <div class="dropdown-divider"></div>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown">
                            {{ request.user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'fairdy:index' %}?username={{ user.username }}">My Simulations</a>
                            <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                            {% if request.user.is_staff %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:user_index' %}">User Admin</a>
                            {% endif %}
                        </div>
                    </li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container-fluid">

            <!-- Message banner -->
            {% if messages %}
                <ul class="messages pl-0 pt-2">
                {% for message in messages %}
                <div class="alert alert-primary alert-dismissible fade show {{ message.tags }}" role="alert">
                        <strong>{{ message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
                </ul>
            {% endif %}
            {% block content %}{% endblock %}

        </main>

    </body>
</html>

web/templates/help.html
{% extends "base.html" %}
{% block title %} Help{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-xl-2 d-none d-lg-block">
                <ul class="nav flex-column">
                    <li>FaiRDy-Py</li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'fairdy:help_getting_started' %}">Getting Started</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'fairdy:help_run_simulation' %}">Running Simulations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'fairdy:help_compare_download' %}">View, Compare, and Download</a>
                    </li>
                    <hr>
                    <li>Accounts</li>
                    <li>
                        <a class="nav-link" href="{% url 'accounts:help_create_account' %}">Create Account</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'accounts:help_manage_account' %}">Manage Account</a>
                    </li>
                    {% if request.user.is_staff %}
                    <li>
                        <a class="nav-link" href="{% url 'accounts:help_manage_users' %}">Manage Users</a>
                    </li>
                    {% endif %}
                </ul>

            </div>
            <div class="col-12 col-lg-9 col-xl-10">
                {% block content_help %}{% endblock %}
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock %}